# Standards: 0.1
---
- name: Fact firefox user
  set_fact:
    firefox_user: "{{ firefox_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - firefox

- become: "{{ (firefox_user != ansible_user_id) | bool }}"
  become_user: "{{ firefox_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: firefox
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - firefox

    - name: Remove quarantine flag
      register: firefox_quarantine
      failed_when: firefox_quarantine.rc != 0 and "No such xattr" not in firefox_quarantine.stderr
      changed_when: firefox_quarantine.rc == 0
      command: xattr -d com.apple.quarantine /Applications/Firefox.app
      tags:
        - firefox

    - name: Install pidof package
      homebrew:
        name: pidof
      tags:
        - firefox

    - name: Check program running
      register: firefox_running
      failed_when: False
      changed_when: firefox_running.stdout | length > 0 | bool
      command: pidof Firefox
      tags:
        - firefox

    - name: Fact program running
      set_fact:
        firefox_started: "{{ firefox_running.stdout_lines | length > 0 | bool }}"
      tags:
        - firefox

...
